# name: Testworkflow

# # Controls when the action will run. Workflow runs when manually triggered using the UI
# # or API.
# on:
#   push: #wenn push
#     branches: ["main"] #nur dieser Branch
#   pull_request: #wenn pull_request
#     branches: ["main"] #nur dieser Branch
#     types: #wenn das oder das passieert
#       - opened
#       - reopened
# jobs:
#   Testjob: #Name
#     runs-on: ubuntu-latest #Auf welcher Plattform der Job l채uft
#     #Welche Schritte ausgef체hrt werden m체ssen
#     steps:
#     - name: Checkout Code #l채dt Code
#       run: actions/checkout@v3

#     - name: Install Go
#       run: sudo apt update && sudo apt install -y golang -go

#     - name: Install Node
#       run: sudo apt install -y nodejs
    
#     - name: Install Trivy
#       run: sudo apt-get install trivy
    
#     - name: Frontend
#       run: cd frontend; npm ci; npx ng build; cd..; cp -r frontend/dist/frontend/browser backend/cmd/strichliste/frontendDist
    
#     - name: Backend
#       run: cd backend; go run ./cmd/strichliste/main.go 
    
#     - name: Tests
#       run: go run ./..; go test ./... -coverprofile=coverage.out && go tool cover -html=coverage.out -o coverage.html

